# Generated by Django 4.1 on 2023-07-18 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("first_app", "0002_alter_blogpost_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="content",
            new_name="text",
        ),
    ]
