# Generated by Django 4.1 on 2023-07-18 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("first_app", "0003_rename_content_blogpost_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blogpost",
            old_name="text",
            new_name="content",
        ),
    ]
